blank_issues_enabled: true
contact_links:
  - name: Discussions & Support
    url: https://talk.newpathconsulting.com/c/wa-discuss/watm/7
    about: You can ask general questions or give feedback here.
  - name: WildApricot Hero Support
    url: https://newpathconsulting.com/hero
    about: Get premium video call support for EZ WildApricot Web Designer.
